### ISSUE TITLE
PhotometricInterpretation YBR_FULL not supported

### ISSUE THREAD

**Issue by aswahd** [radoss-org/radstract#26]
Dicom images with PhotometricInterpretation YBR_FULL are currently not supported.

https://github.com/radoss-org/radstract/blob/080073319336849ea5b9c12232dc8bfd02e618c5/radstract/data/dicom/main.py#L60

**Comment by Sharpz7** [comment]
Related to https://github.com/radoss-org/radstract/issues/6
